Threshold = 95
DisplayMonitorSources = false
EnableUpdates = true
GuiltTripped = false
FilterInput = true
FilterOutput = false
LastUsedInput = "alsa_input.pci-0000_00_1f.3.analog-stereo"
LastUsedOutput = ""
